###
GET http://localhost:9000/equipments/2022-11-01/nightShift
Authorization: Basic c2g0YjFrNDpAOVQ0VHI3MyU2MmwhaUhxZGhXdg==

###
GET https://construck-backend-live.herokuapp.com/works/v3

###
GET http://localhost:9000/downtimes/

###
GET http://localhost:9000/employees/62bacdcc0a8ded52cc67ed5a

###
POST http://localhost:9000/works/getAnalytics
Content-Type: application/json

{
    "startDate": "2022-05-01",
    "endDate": "2022-07-07",
    "status": "approved"
}



###
GET http://localhost:9000/jobtypes/


###
GET http://localhost:9000/vendors/


###
GET http://localhost:9000/works/detailed/true?startDate=2022-10-01&endDate=2022-10-17


###
GET http://localhost:9000/activities/


###
GET http://localhost:9000/reasons/

###
GET http://localhost:9000/assetAvailability/



###
GET http://localhost:9000/works/v3/driver/62bacdcc0a8ded52cc67ed2c


###
GET http://localhost:9000/works/v3

###
GET http://localhost:9000/dispatches/

###
GET http://localhost:9000/logs/


###
POST http://localhost:9000/assetAvailability/
Content-Type: application/json

{
    "date":"16-06-2022",
    "available": 235,
    "unavailable": 0
}



###
POST http://localhost:9000/reasons/
Content-Type: application/json

{
    "description":"Client Related"
    
}


###
POST http://localhost:9000/jobtypes/
Content-Type: application/json

{
    "jobDescription":"Moving other Machines",
    "eqType":"Truck"    
}


###
POST http://localhost:9000/activities/
Content-Type: application/json

{
    "activityDescription":"Compacting"
    
}


###
POST http://localhost:9000/equipments/
Content-Type: application/json

{
    "plateNumber": "RAD 758 Z",
    "eqDescription": "LOWBED",
    "assetClass": "CONSTRUCTION MACHINE",
    "eqtype": "Machine",
    "eqOwner": "HYBRID ENGINEERING LTD",
    "eqStatus": "standby",
    "rate": 600000,
    "supplierRate": 150000,
    "uom": "day"
}

###
POST http://localhost:9000/customers/project
Content-Type: application/json

{
    "id": "626003bd74e53acb4eac8719",
    "project" : {
        "prjDescription": "RUBAVU WORLD BANK",
        "status": "ongoing"
    }
    
}


###
POST http://localhost:9000/customers/
Content-Type: application/json

{
    "name": "RUTAYISIRE JMV",
    "phone":"0788303629",
    "email":"rgakwandi@gmail.com",
    "tinNumber":"2222"
}



###
POST http://localhost:9000/vendors/
Content-Type: application/json

{
    "name":"GAHIMA BALINDA INNOCENT",
    "phone":"0788469688",
    "password":"$2a$10$sDKLYeUih.Ee0Gxt1CRhk.I.d04TQjEkO.pYmj5k63o2GpMjN38RK"
}


###
POST http://localhost:9000/users
Content-Type: application/json

{
    "firstName":"IYAKAREMYE",
    "lastName":"BENJAMIN",
    "username":"biyakaremye",
    "password":"password",
    "email":"biyakaremye@construck.rw",
    "phone":"0788406929",
    "userType":"admin",
    "company":"626003bd74e53acb4eac8719",
    "status":"active"
}



###
POST http://localhost:9000/employees
Content-Type: application/json

{
    "firstName":"NIYONZIMA",
    "lastName":"PATRICK",
    "username":"pniyonzima",
    "password":"password",
    "email":" ",
    "phone":"0785253919",
    "type":"driver",
    "title": "DRIVER - TRUCK",
    "status":"active"
}


###
POST http://localhost:9000/employees/login
Content-Type: application/json

{
    "password":"password",
    "phone":"0788610243"
}

###
PUT http://localhost:9000/employees/token/62bacdcc0a8ded52cc67ed2f
Content-Type: application/json

{
    "employee":"62bacdcc0a8ded52cc67ed38",
    "token":"0783575588"
}

###
GET http://localhost:9000/employees/token/62bacdcc0a8ded52cc67ed33
Content-Type: application/json

{
    "employee":"62bacdcc0a8ded52cc67ed38",
    "token":"0783575588"
}



###
POST http://localhost:9000/users/login
Content-Type: application/json

{
    "password":"password",
    "email":"biyakaremye@construck.rw"
}



###
PUT http://localhost:9000/users/status
Content-Type: application/json

{
    
    "user":{
    "status": "inactive",
    "_id": "6256b969b1de6f0b83c3c4b4",
    "fistName": "Bruce",
    "lastName": "Higiro",
    "username": "bhigiro",
    "password": "$2a$10$hcYw1TTtZAXtMdozpJ1u/eDog.lJgkI.UKqHCD9kbzYZVvXsYFdmW",
    "email": "higiro@gmail.com",
    "phone": "0783575582",
    "userType": "driver",
    "company": "construck",
    "createdOn": "2022-04-13T11:51:55.070Z",
    "__v": 0
  },
    "status":"active"
}


###
POST http://localhost:9000/projects
Content-Type: application/json

{
    "prjDescription":"KIP/MAINTENANCE OF CITY ROADS",
    "customer":"626003bd74e53acb4eac8719",
    "startDate": "2022-04-13T11:20:19.858Z",
    "endDate":"2022-12-31T11:20:19.858Z",
    "status":"ongoing"
}

###
GET http://localhost:9000/projects/releasedRevenue/KIP KACYIRU BY PASS?month=7&year=2022
Authorization: Basic c2g0YjFrNDpAOVQ0VHI3MyU2MmwhaUhxZGhXdg==


###
GET http://localhost:9000/projects/worksToBeValidated/KIP KACYIRU BY PASS
Authorization: Basic c2g0YjFrNDpAOVQ0VHI3MyU2MmwhaUhxZGhXdg==


###
POST http://localhost:9000/works
Content-Type: application/json

{
    "project":"62600a53e140d26799f2db2e",
    "equipment":"6256aeb2ac1b8e911a9a56c0",
    "workDone":"Excavation",
    "startIndex":"99289",
    "endIndex":"99490",
    "driver":"6260051e74e53acb4eac871b",
    "dispatch":"62669216fb920b6909ecbccc",
    "status":"in progress"
}

###
PUT http://localhost:9000/works/start/62a06a49f169107671a1aaf4
Content-Type: application/x-www-form-urlencoded


###
PUT http://localhost:9000/works/reverse/62dd534b3281390c0b6aaefb
Content-Type: application/x-www-form-urlencoded


###
POST http://localhost:9000/dispatches
Content-Type: application/json

{
    "dispatchDescription":"Trucks for Soil removal2",
    "project":"62600a53e140d26799f2db2e",
    "fromSite":"",
    "toSite":"",
    "targetTrips":"8",
    "drivers":[{  "_id": "6260051e74e53acb4eac871b",  "firstName": "Bruce",  "lastName": "Higiro2",  "username": "bhigiro2",  "password": "$2a$10$ZBS1QnZmc/xPVjB91GaIuu9QzL1f5wh1Am3FgNYr0Wu64EKw0oZCe",  "email": "bruce@gmail.com",  "phone": "0783575582",  "userType": "driver",  "company": "626003bd74e53acb4eac8719" ,  "status": "active",  "createdOn": "2022-04-20T12:54:53.182Z"}],
    "equipments":[{  "_id":  "625e7e3f5530102327618fb5",  "plateNumber": "RAF345A",  "eqtype": "Truck",  "eqOwner": "Construck",  "eqStatus": "standby",  "rate": 10000,  "createdOn":  "2022-04-19T09:02:53.285Z"}]
}


###
PUT http://localhost:9000/equipments/makeAllAvailable

###
PUT http://localhost:9000/equipments/syncWorkshopStatus


###
POST http://localhost:9000/assetAvailability/getAnalytics
Content-Type: application/json

{
    "startDate": "01-JUL-2022",
    "endDate": "29-JUL-2022"
}


###
DELETE http://localhost:9000/equipments/hired


###
POST http://localhost:9000/email/send
Content-Type: application/json

{
    "from":"info@construck.rw", 
    "to":"bhigiro@cvl.co.rw", 
    "subject":"Password reset", 
    "messageType":"passwordReset", 
    "password":"Welcome@123"
}

###
PUT http://localhost:9000/users/
Content-Type: application/json

{
    "email":"biyakaremye@construck.rw",
    "oldPassword": "password",
    "newPassword":"password1",
    "reset": "true"
}



###
POST http://localhost:9000/downtimes/getAnalytics
Content-Type: application/json

{
    "startDate": "2022-08-01",
    "endDate": "2022-08-30"
}

###
POST http://localhost:9000/downtimes/trucks
Content-Type: application/json

{
    "startDate": "2022-11-01",
    "endDate": "2022-08-30"
}


###
POST http://localhost:9000/works/gethoursperdriver
Content-Type: application/json

{
    "startDate": "2022-06-01",
    "endDate": "2022-12-31"
}

###
PUT http://localhost:9000/works/driverassistants


###
GET http://localhost:9000/works/v3/toreverse/RAE 746 K?startDate=2022-07-01&endDate=2022-12-31
Authorization: Basic c2g0YjFrNDpAOVQ0VHI3MyU2MmwhaUhxZGhXdg==
Content-Type: application/json

{
    "startDate": "2022-07-10",
    "endDate": "2022-12-31"
}


###
PUT http://localhost:9000/works/amend/6347c57be790ec5e892456fe
Authorization: Basic c2g0YjFrNDpAOVQ0VHI3MyU2MmwhaUhxZGhXdg==
Content-Type: application/json

{ "tripsDone":"3", "comment":"Updates", "moreComment":"", "stoppedBy":"62ba73314866f297799e1816", "duration":"5" }

###
GET http://localhost:9000/works/detailed/monthlyRevenuePerProject/KIP KACYIRU BY PASS?status=validated
Authorization: Basic c2g0YjFrNDpAOVQ0VHI3MyU2MmwhaUhxZGhXdg==
Content-Type: application/json



###
GET http://localhost:9000/works/monthlyRevenuePerProject/KIP KACYIRU BY PASS?status=validated
Authorization: Basic c2g0YjFrNDpAOVQ0VHI3MyU2MmwhaUhxZGhXdg==
Content-Type: application/json

{
    "status": "validated"
}


###
PUT http://localhost:9000/works/releaseValidated/KIP KACYIRU BY PASS?month=10&year=2022
Authorization: Basic c2g0YjFrNDpAOVQ0VHI3MyU2MmwhaUhxZGhXdg==
Content-Type: application/json

###
GET http://localhost:9000/works/monthlyNonValidatedRevenues/KIP KACYIRU BY PASS
Authorization: Basic c2g0YjFrNDpAOVQ0VHI3MyU2MmwhaUhxZGhXdg==
Content-Type: application/json

###
GET http://localhost:9000/works/nonValidatedByDay/KIP KACYIRU BY PASS?transactionDate=2022-10-30T00:00:00.000Z
Authorization: Basic c2g0YjFrNDpAOVQ0VHI3MyU2MmwhaUhxZGhXdg==
Content-Type: application/json

###
GET http://localhost:9000/works/dailyNonValidatedRevenues/KIP KACYIRU BY PASS?month=10&year=2022
Authorization: Basic c2g0YjFrNDpAOVQ0VHI3MyU2MmwhaUhxZGhXdg==
Content-Type: application/json